/**
 * Swagger (OpenAPI) type exports.
 *
 * Source of truth: `cricketclub.json` (checked into the repo root).
 *
 * These types are generated by `openapi-typescript` into `src/api/generated/openapi.ts`.
 *
 * Regenerate with:
 *   npm run generate:openapi
 */

import type { components } from './generated/openapi';

// Common schema aliases
export type AwardV1 = components['schemas']['AwardV1'];
export type CommitteePostV1 = components['schemas']['CommitteePostV1'];
export type MatchV1 = components['schemas']['MatchV1'];
export type PlayerV1 = components['schemas']['PlayerV1'];
export type ResultV1 = components['schemas']['ResultV1'];
export type TeamV1 = components['schemas']['TeamV1'];
export type TeamDetailV1 = components['schemas']['TeamDetailV1'];
export type TeamSummaryV1 = components['schemas']['TeamSummaryV1'];
export type VenueV1 = components['schemas']['VenueV1'];
export type VenueStatsV1 = components['schemas']['VenueStatsV1'];
export type VenueSummaryV1 = components['schemas']['VenueSummaryV1'];
export type VenueDetailV1 = components['schemas']['VenueDetailV1'];

// Live scoring
export type LiveScorecardV1 = components['schemas']['LiveScorecardV1'];
export type InPlayLiveScorecardV1 = components['schemas']['InPlayScorecardV1'];
export type MatchScorecardV1 = components['schemas']['MatchScorecardV1'];
export type MatchReportV1 = components['schemas']['MatchReportV1'];
export type BattingEntryV1 = components['schemas']['BattingEntryV1'];
export type BowlingEntryV1 = components['schemas']['BowlingEntryV1'];
export type ExtrasV1 = components['schemas']['ExtrasV1'];
export type WicketV1 = components['schemas']['WicketV1'];
export type BowlerInningsDetailsV1 = components['schemas']['BowlerInningsDetailsV1'];
export type BatsmanInningsDetailsV1 = components['schemas']['BatsmanInningsDetailsV1'];
export type FoWEntryV1 = components['schemas']['FoWEntryV1'];
export type OverSummaryV1 = components['schemas']['OverSummaryV1'];
export type OverV1 = components['schemas']['OverV1'];
export type BallV1 = components['schemas']['BallV1'];

// Scorecard editing types
export type MatchDropV1 = components['schemas']['MatchDropV1'];
export type InningsScoreCardV1 = components['schemas']['InningsScoreCardV1'];
export type BattingCardV1 = components['schemas']['BattingCardV1'];
export type BowlingCardV1 = components['schemas']['BowlingCardV1'];
export type FoWV1 = components['schemas']['FoWV1'];
export type FoWPlayerV1 = components['schemas']['FoWPlayerV1'];
export type MatchConditionsV1 = components['schemas']['MatchConditionsV1'];

// Live scoring app types
export type MatchStateV1 = components['schemas']['MatchStateV1'];
export type MatchStateUpdateV1 = components['schemas']['MatchStateUpdateV1'];
export type PlayerStateV1 = components['schemas']['PlayerStateV1'];
export type PartnershipStubV1 = components['schemas']['PartnershipStubV1'];
export type BallByBallMatchConditionsV1 = components['schemas']['BallByBallMatchConditionsV1'];
export type LiveScoringMatchSummaryV1 = components['schemas']['LiveScoringMatchSummaryV1'];
export type BallByBallMatchDescriptorV1 = components['schemas']['BallByBallMatchDescriptorV1'];
export type OppositionInningsDetailsV1 = components['schemas']['OppositionInningsDetailsV1'];
export type InningsEndDetailsV1 = components['schemas']['InningsEndDetailsV1'];
export type AbandonMatchV1 = components['schemas']['AbandonMatchV1'];
export type YetToBatEntryV1 = components['schemas']['YetToBatEntryV1'];
