/**
 * Swagger (OpenAPI) type exports.
 *
 * Source of truth: `cricketclub.json` (checked into the repo root).
 *
 * These types are generated by `openapi-typescript` into `src/api/generated/openapi.ts`.
 *
 * Regenerate with:
 *   npm run generate:openapi
 */

import type { components } from './generated/openapi';

// Common schema aliases
export type AwardV1 = components['schemas']['AwardV1'];
export type CommitteePostV1 = components['schemas']['CommitteePostV1'];
export type MatchV1 = components['schemas']['MatchV1'];
export type PlayerV1 = components['schemas']['PlayerV1'];
export type ResultV1 = components['schemas']['ResultV1'];
export type TeamV1 = components['schemas']['TeamV1'];
export type VenueV1 = components['schemas']['VenueV1'];

// Live scoring
export type LiveScorecardV1 = components['schemas']['LiveScorecardV1'];
export type InPlayLiveScorecardV1 = components['schemas']['InPlayScorecardV1'];
export type MatchScorecardV1 = components['schemas']['MatchScorecardV1'];
export type MatchReportV1 = components['schemas']['MatchReportV1'];
export type BattingEntryV1 = components['schemas']['BattingEntryV1'];
export type BowlingEntryV1 = components['schemas']['BowlingEntryV1'];
export type ExtrasV1 = components['schemas']['ExtrasV1'];
export type WicketV1 = components['schemas']['WicketV1'];
export type BowlerInningsDetailsV1 = components['schemas']['BowlerInningsDetails'];
export type BatsmanInningsDetailsV1 = components['schemas']['BatsmanInningsDetails'];
export type FoWEntryV1 = components['schemas']['FoWEntryV1'];
export type OverSummaryV1 = components['schemas']['OverSummaryV1'];
export type OverV1 = components['schemas']['OverV1'];
export type BallV1 = components['schemas']['BallV1'];

// Scorecard editing types
export type InningsScoreCardV1 = components['schemas']['InningsScoreCardV1'];
export type BattingCardV1 = components['schemas']['BattingCardV1'];
export type BowlingCardV1 = components['schemas']['BowlingCardV1'];
export type FoWV1 = components['schemas']['FoWV1'];
export type FoWPlayerV1 = components['schemas']['FoWPlayerV1'];
export type MatchConditionsV1 = components['schemas']['MatchConditionsV1'];
